version: '3.8'

services:

  mysql:
    ports:
      - '4306:3306'

  php:
    build:
      args:
        WWW_DATA_UID: 1000
        WWW_DATA_GID: 1000

  nginx:
    ports:
      - "8009:80"

  adminer:
    image: adminer
    ports:
      - 9011:8080