version: '3.8'

services:
  mysql:
     image: mariadb:10.8.3
     command: --default-authentication-plugin=mysql_native_password
     environment:
      MYSQL_ROOT_PASSWORD: root
     volumes:
        - ./docker/mysql:/var/lib/mysql

  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:stable-alpine

    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf


